name: Check Create Branch Request

on:
  create:
jobs:
  check_create_branch:
    runs-on: ubuntu-latest
    steps:
      - name: Check if pushed branch name is ok
        run: |
          branch_name=${GITHUB_REF#refs/heads/}  # Get the branch name from GITHUB_REF
          echo "Pushed branch name: $branch_name"
          
          # Define regex patterns for the new naming conventions
          feature_regex="^feature/[a-z0-9\-]+$"
          bugfix_regex="^bugfix/[a-z0-9\-]+$"
          release_regex="^release/[v0-9]+\.[0-9]+\.[0-9]+$"
          hotfix_regex="^hotfix/[a-z0-9\-]+$"
          
          # Check if the branch name matches any of the above patterns
          if [[ "$branch_name" =~ $feature_regex ]]; then
            echo "Branch name matches the 'feature' pattern."
          elif [[ "$branch_name" =~ $bugfix_regex ]]; then
            echo "Branch name matches the 'bugfix' pattern."
          elif [[ "$branch_name" =~ $release_regex ]]; then
            echo "Branch name matches the 'release' pattern."
          elif [[ "$branch_name" =~ $hotfix_regex ]]; then
            echo "Branch name matches the 'hotfix' pattern."
          else
            echo "Branch name does not match any recognized pattern. Exiting..."
            git -d branch $branch_name
            exit 1
          fi
        shell: bash
