name: Check Create Branch Request

on:
  create:
jobs:
  check_create_branch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      
      - name: Set default branch name
        run: echo "branch_name=${{ github.ref }}" >> $GITHUB_ENV

      - name: Check branch name is ok
        id: check_branch_name
        run: |
          branch_name=${GITHUB_REF#refs/heads/}  # Get the branch name from GITHUB_REF
          echo "Pushed branch name: $branch_name"
          
          # shopt -s nocasematch  # Make the regex pattern matching case-insensitive
          
          # Define regex patterns for the new naming conventions
          feature_regex="^[0-9]+\.[0-9]+\.[0-9]/Feature/[A-Za-z0-9\-]+$"
          tech_enhancement_regex="^[0-9]+\.[0-9]+\.[0-9]+/Tech-Enhancement/[A-Za-z0-9\-]+$"
          uix_enhancement_regex="^[0-9]+\.[0-9]+\.[0-9]+/UIX-Enhancement/[A-Za-z0-9\-]+$"
          planned_fix_regex="^[0-9]+\.[0-9]+\.[0-9]+/Fix/[A-Za-z0-9\-]+$"
          crashlytics_regex="^[0-9]+\.[0-9]+\.[0-9]+/crash/[A-Za-z0-9\-]+$"

          # Check if the branch name matches any of the above patterns
          if [[ "$branch_name" =~ $feature_regex ]]; then
            echo "Branch name matches the 'Feature' pattern."
          elif [[ "$branch_name" =~ $tech_enhancement_regex ]]; then
            echo "Branch name matches the 'Tech Enhancement' pattern."
          elif [[ "$branch_name" =~ $uix_enhancement_regex ]]; then
            echo "Branch name matches the 'UI/UX Enhancement' pattern."
          elif [[ "$branch_name" =~ $planned_fix_regex ]]; then
            echo "Branch name matches the 'Planned Fix' pattern."
          elif [[ "$branch_name" =~ $crashlytics_regex ]]; then
            echo "Branch name matches the 'Crashlytics' pattern."
          else
            echo "Branch name does not match any recognized pattern. Exiting..."
            exit 1
          fi

          # Export the branch name to be used in the next step
          echo "branch_name=$branch_name" >> $GITHUB_ENV

      - name: Delete Branch if Invalid Naming Convention
        if: failure()  # Only run if the previous step fails (i.e., invalid branch naming)
        uses: dawidd6/action-delete-branch@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branches: ${{ github.ref }}