name: Notify for Inactive Branches

on:
  schedule:
    - cron: "0 0 * * 0"  # Runs every Sunday at midnight
  workflow_dispatch:  # Allow manual triggering of the action

jobs:
  check-inactive-branches:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Get Inactive Branches
        run: |
          git fetch --all
          current_date=$(date +%s)
          echo "Inactive branches exceeding 30 days:" > inactive_branches.txt

          for branch in $(git for-each-ref --sort=-committerdate --format='%(refname:short) %(committerdate:unix)' refs/heads/); do
            branch_name=$(echo $branch | awk '{print $1}')
            branch_date=$(echo $branch | awk '{print $2}')
            branch_age=$(( (current_date - branch_date) / (60 * 60 * 24) ))

            if [ "$branch_age" -gt 30 ]; then
              echo "$branch_name (inactive for $branch_age days)" >> inactive_branches.txt
            fi
          done

          cat inactive_branches.txt
          echo "::set-output name=inactive_branches::$(cat inactive_branches.txt | tr '\n' '|')"

      - name: Send Email Notification
        if: success()
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 587 # Default SMTP port / 465 for SSL
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: Inactive Git Branches Notification
          to: "ali.hammoud@et3arraf.com"
          from: "ali.hammoud@et3arraf.com"
          body: |
            Hello Team,

            The following branches have been inactive for over 30 days:

            ${{ steps.get-inactive-branches.outputs.inactive_branches | replace('|', '\n') }}

            Please review and take appropriate action.

            regards,

            Ali Hammoud (DevOps Engineer)
